---
title: "my rmarkdown"
author: "Ziheng"
date: "2019/7/1"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Download data

Download sleep study data
```{r}
library(readr)
sleep <- read_csv(
  "https://vincentarelbundock.github.io/Rdatasets/csv/lme4/sleepstudy.csv")
head(sleep)
```

Plot the data by subject
```{r}
library(ggplot2)
ggplot(sleep, aes(x = Days, y = Reaction)) +
  geom_point() +
  geom_smooth() +
  scale_x_continuous(breaks = seq(0, 8, by = 2)) +
  facet_wrap(~ Subject)
```


```{r}
library(dplyr)
sleep %>%
  group_by(Subject) %>%
  summarise(mean(Reaction))
```

Mean-center reaction times and plot on a single axis
```{r}
sleep %>%
  group_by(Subject) %>%
  mutate(mean_centered_reaction = Reaction - mean(Reaction)) %>%
  ggplot(aes(x = Days, y = mean_centered_reaction, col = factor(Subject))) +
    geom_smooth(show.legen = FALSE, se = FALSE) +
    scale_x_continuous(breaks = seq(0, 8, by = 2))
```

